version: "3.9"

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resort_booking
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: resort_app
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 010502dd
      POSTGRES_DB: resort_booking
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

volumes:
  postgres_data:
