"""room_number

Revision ID: 2803228606b8
Revises: 4a7cc4358212
Create Date: 2025-05-15 22:58:58.181266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2803228606b8'
down_revision: Union[str, None] = '4a7cc4358212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stay_records', sa.Column('room_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stay_records', 'room_number')
    # ### end Alembic commands ###
