"""stay_record_name

Revision ID: a1c9919ca570
Revises: e54e0a99b164
Create Date: 2025-05-15 00:46:03.701717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c9919ca570'
down_revision: Union[str, None] = 'e54e0a99b164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stay_records', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stay_records', 'name')
    # ### end Alembic commands ###
